### PR TITLE
Add spm support

### PR DESCRIPTION
**Pull request by afc163**
A nice package manager: http://spmjs.io
Documentation: http://spmjs.io/documentation

http://spmjs.io/package/whatwg-fetch

---

It is a browser-side package manager popular in China, suppling a complete lifecycle managment of package via [spm](https://github.com/spmjs/spm/tree/master).

> If you need ownership of whatwg-fetch in spmjs, I would like add it for your account after signing in http://spmjs.io.

spmjs/spm#781

### CODE REVIEW

**Comment by afc163** [comment]
ping~

**Comment by mislav** [comment]
Sorry about the silence. Personally, I'm :-1: on adding docs and `package.json` support for yet another package manager that we haven't heard about. But I'll let @josh @dgraham reach a decision.

**Comment by dgraham** [comment]
It seems like new JS package managers would need to support existing package manifest syntax in order to gain adoption. I'm closing this because we support two manifest formats today: bower and npm.

**Comment by afc163** [comment]
OK, thx for reply :+1:

**Pull request closed without merging**
