### PR TITLE
Add webpack usage link.

### LINKED ISSUE #193: Document usage instructions with popular module loaders (Webpack, Browserify, etc.)
It looks like the README used to have instructions on usage with Browserify, but it has been removed for reasons I don't understand: https://github.com/github/fetch/commit/01797bceb6e07d0a0b2090915c4cd0df52f7bb5d

It can be difficult to figure out how to use a global-attaching polyfill in Webpack or Browserify. Adding these instructions to the README would be very helpful. I'd be happy to contribute updated instructions if the PR would be accepted :)

Previous PRs:

- Webpack instructions (closed for unknown reasons): https://github.com/github/fetch/pull/110
- Browserify instructions (potentially still accurate, outside of module name): https://github.com/github/fetch/blob/4b9e44493cfcab97077dd2d7be6a8364292ea03a/README.md#using-with-npm-and-browserify

### PR DESCRIPTION
**Pull request by dgraham**
Closes #193. Thanks for documenting this, @matiassingers.

### CODE REVIEW

**Comment by matiassingers** [comment]
Cool! :+1:

**Comment by minhngan** [comment]
G

**Comment by minhngan** [comment]
Goot 😉

**Pull request merged**
