### PR TITLE
fix example

### PR DESCRIPTION
**Pull request by vga-**
fixes example to use api.github.com rather than github.com

### CODE REVIEW

**Comment by mislav** [comment]
The example URL is just for demonstration purposes only. It doesn't really matter what the exact URL is. People are to substitute their own URL in this field. The URL `github.com` works well as an example because it's simple and also refers to the entity behind this project.

**Comment by vga-** [comment]
Shouldn't the example at least work if someone copies and pastes it?

**Comment by mislav** [comment]
You're right! `api.github.com` allows for CORS and therefore will work when `github.com` doesn't. Thanks!

**Comment by mislav** [comment]
@dgraham Ah, thanks for that bit of context. @vga- It would have been helpful to me if you linked to the prior discussion when opening the PR. More context around the proposed change always helps!

**Comment by vga-** [comment]
Okay, thanks! I'll make sure to do that in the future.

**Pull request merged**
