### PR TITLE
Add metadata for repository, bugs and license

### PR DESCRIPTION
**Pull request by danez**
This would be nice as this information is displayed in the npm repository.

### CODE REVIEW

**Comment by domenic** [comment]
bugs is redundant with repository and repository can just be `"repository": "github/fetch"`

**Comment by danez** [comment]
Oh I haven't checked that in detail, will do it later.

**Comment by danez** [comment]
@domenic I couldn't find any reference on what you said, all examples state, you should us a full url to your repository. And bugs is a different url that is used by ```git bugs```

**Comment by domenic** [comment]
It's correct, but it's way longer than it needs to be, and a maintenance burden.

Here's another official package or three you can copy markup from:

- https://github.com/domenic/webidl-class-generator/blob/master/package.json#L9
- https://github.com/domenic/sinon-chai/blob/master/package.json#L15
- https://github.com/tmpvar/jsdom/blob/master/package.json#L57

**Comment by domenic** [comment]
And here's the docs: https://github.com/npm/normalize-package-data#what-normalization-currently-entails

**Comment by danez** [comment]
Seems this shorter way of defining the guthub repository is not covered in the official docs about package.json.
Now its changed.

**Comment by josh** [comment]
cools

**Pull request merged**
