### PR TITLE
Open

### PR DESCRIPTION
**Pull request by drvsinan**

### CODE REVIEW

**Review by drvsinan — COMMENTED** [review]
Onayla

**Review by DAIDAOXING — APPROVED** [review]
FOR EXAMPLE OF DAI DAOXING

**Review by DannyLedbetter — APPROVED** [review]

**Comment by AidensM** [comment]
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/issues/comments

**Comment by Asman3316** [comment]
No concted trasutwallet

**Pull request closed without merging**
