### PR TITLE
added timeout support

### PR DESCRIPTION
**Pull request by Gcaufy**
it's really useful to add a timeout option.

### CODE REVIEW

**Comment by mislav** [comment]
Thanks, but we can't accept a feature that's not in the spec! See https://github.com/github/fetch#read-this-first and https://github.com/github/fetch/issues/175#issuecomment-125779262 https://github.com/github/fetch/issues/405 https://github.com/github/fetch/issues/246 https://github.com/github/fetch/issues/181 https://github.com/github/fetch/pull/68 https://github.com/github/fetch/issues/16 for background.

**Comment by Gcaufy** [comment]
ok, got it.

**Comment by fritx** [comment]
Excuse me, how could we increase timeout to Infinity or over 120s which is default value of Chrome?

I couldn't find out a solution from those issues :/

**Comment by Gcaufy** [comment]
you can use Promise.race instead.

```
const fetchTimeout = (p, time) => {
    let timeout = new Promise((resolve, reject) => { 
        setTimeout(() => reject(new Error('timeout')), time); 
    });
    return Promise.race([p, timeout]);
};


fetchTimeout(fetch({}), 3000).then()
```

**Comment by fritx** [comment]
@Gcaufy your code looks like to declare a timeout instead, but I want to drop any timeout that would exists. Am I missing anything?

**Comment by Gcaufy** [comment]
this is like 
```
axios({timeout: 3000})
```

so I guess what you need is
```
axios.defaults.timeout = 3000
```
or a common call back, like: 
```
fetch.globalTimeoutCallback = () => {
   console.log('this is timeout');
}
```

what ever you need, you can use Promise.race get what you want:
e.g.
```
const reqest = (p, time = null) => {
   time = time || fetch.defaults.timeout;
   if (!time) return p;
   let timer;
   let timePromise = new Promise((resolve, reject) => {
     timer = setTimeout(() => {
        fetch.globalTimeoutCallback();
        reject(new Error('timeout'));
    }, time)
   });
   return Promise.race([p.then(res => {
        clearInterval(timer);
        return res;
    ), timer])
}
```

**Comment by jimmywarting** [comment]
actually, this is what you should be doing:

```js
const controller = new AbortController()
const signal = controller.signal
setTimeout(() => { 
  controller.abort()
}, 1000)

fetch(url, { signal })
```

**Pull request closed without merging**
