### PR TITLE
Allow `:` in headers

### PR DESCRIPTION
**Pull request by XadillaX**
Here's a request's header:

```
:authority:jandan.net
:method:GET
:path:/ooxx
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8

...
```

see https://jandan.net/ooxx

### CODE REVIEW

**Comment by XadillaX** [comment]
anyone to review this code?

**Comment by mislav** [comment]
The `:` character should not be allowed in header names. Why do you need this?

**Comment by XadillaX** [comment]
Imagine I am a crawler. And open this page in Chrome:

https://jandan.net/ooxx

Open developer tools and see the Network.

image

I should simulate it but failed with `fetch`.

**Comment by XadillaX** [comment]
How's the result?

**Comment by dgraham** [comment]
This [StackOverflow post](http://stackoverflow.com/questions/19028068/illegal-characters-in-http-headers#19028585) and linked RFCs define a header `field-name` as a `token`, which is any character except control characters and separators, including the colon. So I don't think we should add this separator character to the regular expression.

**Comment by XadillaX** [comment]
So as a crawler, how could I simulate the request to https://jandan.net/ooxx by using **fetch**? Because that website need this header.

**Pull request closed without merging**
