### PR TITLE
README: + matthew-andrews/isomorphic-fetch

### PR DESCRIPTION
**Pull request by tomByrer**
[No blob](https://github.com/bitinn/node-fetch/issues/78) support in node-fetch.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
This seems unlikely…  Isomorphic fetch *is* node fetch

**Comment by dgraham** [comment]
I think the limitations of other packages should be documented in their README files rather than this one. There also seems to be some confusion between the isomorphic-fetch and node-fetch libraries, and not having used them personally, I'm not sure what to do here.

@matthew-andrews If you think this project link is helpful, I can reopen and merge, but I'm closing for now.

**Comment by mislav** [comment]
Isomorphic-fetch seems to have more stars on GitHub. Maybe we could link to both as alternative implementations, but without any commentary, i.e. avoid mentioning that one supports Blob and the other doesn't. The reader is required to do their own research.

**Comment by tomByrer** [comment]
More information would have been helpful for me, more so if there hadn't
been open issues to look though.

**Comment by mislav** [comment]
> More information would have been helpful for me

I understand. We just don't want to maintain any particulars of a feature set for a library we're not responsible for. If node-fetch supported Blob tomorrow, our Readme would be outdated.

**Pull request closed without merging**
