### PR TITLE
Renamed `self` to `window` since we're in a browser environment and want to support jsdom/jsdomify

### LINKED ISSUE #238: rename self to window
otherwise we can't have tests that run on a node runtime environment simulating a browser (e.g. using jsdom or jsdomify)

### PR DESCRIPTION
**Pull request by niftylettuce**
Closes #238

### CODE REVIEW

**Comment by niftylettuce** [comment]
Looks like tests fail because of iframes or something?

```log
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL
```

**Comment by mislav** [comment]
Sorry, but `self` was used to enable this polyfill working in [a web worker environment](https://github.com/github/fetch/blob/133bd7321019cd825989ad8dcab8c96725e0b612/test/test-worker.html).

We're sorry that you're having problems with jsdom/jsdomify, but we can't help you with that. Our polyfill works quite fine when loaded normally onto the page with `<script src>` tags. If your tools can't handle normal js files, maybe it's time to revisit your tools?

**Comment by mislav** [comment]
Also see #231 #47 #31

**Comment by niftylettuce** [comment]
Is there not a way you can ensure a fallback instead of `self`?  Why can't you?  This doesn't seem right.  Otherwise I have to rely on my fork to get my tests to pass for https://github.com/niftylettuce/frisbee.

**Comment by niftylettuce** [comment]
`if (typeof window === 'object') self = window;`?

**Comment by niftylettuce** [comment]
It really doesn't make sense to me to use `self` JUST to make your tests pass.  That's not right.

**Comment by niftylettuce** [comment]
@mislav yeah I have to stop using `jsdomify` and run it per https://github.com/tmpvar/jsdom/issues/1203#issuecomment-160730614 and just use pure `jsdom` with proper `window` environment.

**Comment by niftylettuce** [comment]
ignore this PR.

**Comment by mislav** [comment]
> Is there not a way you can ensure a fallback instead of `self`? Why can't you? This doesn't seem right.

We welcome a PR that solves the compatibility issue you're describing in an elegant way while at the same time preserving compatibility with Web Workers. The existing CI test suite must pass.

**Pull request closed without merging**
