### PR TITLE
Add `user` and `password` options and use for Basic Authentication

### PR DESCRIPTION
**Pull request by leungwensen**
reference: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#open()

### CODE REVIEW

**Comment by mislav** [comment]
Is this per-spec? I can't find evidence of `options.user` and `options.password` being defined in the spec. All I see is them being embedded in the URL.

This will need tests, too.

**Comment by mislav** [comment]
Actually username/password in URLs is not supported either. #119

I don't know what's supported, then.

**Comment by leungwensen** [comment]
It's not per-spec. Feel free to close this pull-request.

Actually I just want to keep some of my simple web services working after upgrade to window.fetch. Is there any plan to support `username:password` feature?

**Comment by dgraham** [comment]
The `XMLHttpRequest` usage is an implementation detail that is not exposed in the `window.fetch` API.

**Pull request closed without merging**
