### PR TITLE
Update caniuse link to use HTTPS and new pattern

### PR DESCRIPTION
**Pull request by Schweinepriester**
Checked the link, skipping the redirect HTTP => HTTPS and to the new pattern this way 0:-)

### CODE REVIEW

**Review by irene459 — COMMENTED** [review]
How do I unsubscribe this shit there is a hacker which is my husband getting in all my stuff changing things so I can't use my phone properly he has disabled a lot of my apps my Face ID to where I can't log in  he's using my Apple I cloud .all this that's set up is not me .I know nothing about this stuff. So I need you to get all this stuff and erase everything and block what ever you need to block. If I have to go report it to police .let me know ASAP

**Comment by bosszhit4l69** [comment]
https://github.com/github/fetch/pull/1087#pullrequestreview-826221804

**Comment by bosszhit4l69** [comment]
[](url)https://github.com/github/fetch/pull/1087#pullrequestreview-826221804

**Comment by musakuw** [comment]
- [

**Pull request merged**
