### PR TITLE
Add ES2015+ example

### PR DESCRIPTION
**Pull request by jamonholmgren**
I had the same question as @abimelex in #275, and figured it would be useful to have a short example in the README.

### CODE REVIEW

**Comment by mislav** [comment]
I don't think that the instructions for loading this polyfill are different from any other polyfill out there (no exports). Therefore I don't find this particularly useful. But if people are constantly looking this up, then I guess it can't hurt to clear this up. Thoughts @dgraham?

**Comment by jamonholmgren** [comment]
You're right, it's no different than other polyfills...this was the first polyfill I've used within our new Babel environment, so it was the first time I'd considered this question.

**Comment by dgraham** [comment]
Several people have found the answer in #275 useful, so promoting it to the README might help people importing modules for side effects, like adding window global polyfills.

**Comment by jamonholmgren** [comment]
Thank you!

**Pull request merged**
