### PR TITLE
Timeout - candidate for spec

### PR DESCRIPTION
**Pull request by wheresrhys**
Proxies to the `xhr.timeout` property

### CODE REVIEW

**Comment by wheresrhys** [comment]
ok - I'll uncomment

**Comment by matthew-andrews** [comment]
:+1:

**Comment by dgraham** [comment]
We need the [Fetch spec](https://fetch.spec.whatwg.org) to describe standard timeout behavior before adding it to the polyfill. I agree it would be useful. You can open an issue at https://github.com/whatwg/fetch.

**Comment by matthew-andrews** [comment]
oops, i think this pull request was meant for our internal fork of fetch.

**Pull request closed without merging**
